# Configuración del Sistema de Recuperación de Documentos Legales

# Configuración de Weaviate para búsqueda vectorial
weaviate:
  enabled: true
  url: "http://localhost:8080"
  api_key: null
  collection_name: "ArticulosLegales"
  embedding_model: "paraphrase-multilingual-MiniLM-L12-v2"
  use_cache: true

# Configuración de Neo4j para búsqueda basada en grafos
neo4j:
  enabled: true
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "password"

# Configuración de BM25 para búsqueda léxica
bm25:
  enabled: true

# Configuración de recuperación y presentación de resultados
retrieval:
  # Número máximo de resultados a mostrar
  top_n: 20
  
  # Pesos para los diferentes métodos de búsqueda (vectorial, grafo, léxico)
  # Incrementamos el peso de la búsqueda por grafo para dar más relevancia a las relaciones temáticas
  weights: [0.4, 0.4, 0.2]
  
  # Guardar resultados en archivos
  save_results: true
  results_dir: "results"
  
  # Estrategia de fusión de resultados
  fusion_strategy: "weighted_max"
  
  # Umbral mínimo de relevancia para incluir resultados
  min_score_threshold: 0.2